export const getProductConstants = {
    PRODUCT_REQUSET : 'PRODUCT_REQUEST',
    PRODUCT_SUCCESS : 'PRODUCT_SUCCESS',
    PRODUCT_FAILURE : 'PRODUCT_FAILURE',
}

export const cartItemConstants = {
    ADD_NEW_CART_ITEM: 'ADD_NEW_CART_ITEM',
    GET_CART_NUMER: 'GET_CART-NUMBER',
    CART_ITEM_INCREASE: 'CART_ITEM_INCREASE',
    CART_ITEM_DECREASE: 'CART_ITEM_DECREASE',
    REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
}